const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('penguin', {
  getStats: () => ipcRenderer.invoke('get-stats'),
  refreshMemory: () => ipcRenderer.invoke('refresh-memory'),
  onStats: (callback) => ipcRenderer.on('stats-update', (_event, stats) => callback(stats)),
  captureRegion: () => ipcRenderer.invoke('capture-region'),
  onCaptureImage: (callback) => ipcRenderer.on('capture-image', (_event, payload) => callback(payload)),
  finishCapture: (rect) => ipcRenderer.send('capture-finish', rect),
  cancelCapture: () => ipcRenderer.send('capture-cancel'),
  onCaptureComplete: (callback) => ipcRenderer.on('capture-complete', (_event, payload) => callback(payload)),
  openCaptureFolder: () => ipcRenderer.invoke('open-capture-folder'),
  launchCalculator: () => ipcRenderer.invoke('launch-calculator'),
  openManager: (view) => ipcRenderer.invoke('open-manager', view),
  openUrl: (url) => ipcRenderer.invoke('open-url', url),
  webSearch: (query) => ipcRenderer.invoke('web-search', query),
  openSystemTool: (kind) => ipcRenderer.invoke('open-system-tool', kind),
  getDefaultBrowser: () => ipcRenderer.invoke('get-default-browser'),
  getProcesses: () => ipcRenderer.invoke('get-processes'),
  terminateProcess: (pid) => ipcRenderer.invoke('terminate-process', pid),
  readClipboardText: () => ipcRenderer.invoke('read-clipboard-text'),
  writeClipboardText: (text) => ipcRenderer.invoke('write-clipboard-text', text),
  openUserFolder: (kind) => ipcRenderer.invoke('open-user-folder', kind),
  managerWindow: (action) => ipcRenderer.send('manager-window', action),
  onManagerNavigate: (callback) => ipcRenderer.on('manager-navigate', (_event, view) => callback(view)),
  readNotes: () => ipcRenderer.invoke('read-notes'),
  saveNotes: (text) => ipcRenderer.invoke('save-notes', text),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  setSetting: (key, value) => ipcRenderer.invoke('set-setting', key, value),
  onTheme: (callback) => ipcRenderer.on('theme-update', (_event, value) => callback(value)),
  onDockState: (callback) => ipcRenderer.on('dock-state', (_event, value) => callback(value)),
  getDockState: () => ipcRenderer.invoke('get-dock-state'),
  dockHover: (hovering) => ipcRenderer.send('dock-hover', hovering),
  getBackends: () => ipcRenderer.invoke('get-backends'),
  installBackends: () => ipcRenderer.invoke('install-backends'),
  previewCleanup: () => ipcRenderer.invoke('preview-cleanup'),
  runCleanup: () => ipcRenderer.invoke('run-cleanup'),
  scanFolder: () => ipcRenderer.invoke('scan-folder'),
  onBackendsChanged: (callback) => ipcRenderer.on('backends-changed', (_event, value) => callback(value)),
  onSecurityProgress: (callback) => ipcRenderer.on('security-progress', (_event, value) => callback(value)),
  expand: (expanded) => ipcRenderer.send('toolbar-expand', expanded),
  hide: () => ipcRenderer.send('hide-toolbar'),
  quit: () => ipcRenderer.send('quit-app'),
});
